-- =============================================================================
-- Migration 006 — AI Content Generation Engine
-- Adds content_packs table (groups 13-format generation runs) and extends
-- content_ideas with pack_id, format_slug, output_style, structured_data.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. content_packs — one row per generation run
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS content_packs (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cluster_id            uuid NOT NULL REFERENCES trend_clusters(id) ON DELETE CASCADE,
  org_id                uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

  -- Generation config
  output_style          text NOT NULL DEFAULT 'mainstream' CHECK (
    output_style IN ('mainstream', 'savage', 'safer', 'editorial', 'deadpan', 'mock_serious')
  ),
  model_used            text,
  prompt_version        text,
  prompt_template_id    uuid REFERENCES prompt_templates(id) ON DELETE SET NULL,

  -- Usage tracking
  tokens_used           int,
  estimated_cost_usd    numeric(10, 6),
  generation_time_ms    int,

  -- Status lifecycle
  status                text NOT NULL DEFAULT 'generating' CHECK (
    status IN ('generating', 'complete', 'failed', 'partial')
  ),
  error_message         text,

  created_by            uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE content_packs IS 'Groups all 13 AI-generated content formats from a single generation run for a trend cluster.';

CREATE INDEX IF NOT EXISTS idx_content_packs_cluster_id ON content_packs(cluster_id);
CREATE INDEX IF NOT EXISTS idx_content_packs_org_id     ON content_packs(org_id);
CREATE INDEX IF NOT EXISTS idx_content_packs_status     ON content_packs(status);
CREATE INDEX IF NOT EXISTS idx_content_packs_created_at ON content_packs(created_at DESC);

-- ---------------------------------------------------------------------------
-- 2. Extend content_ideas with new columns
-- ---------------------------------------------------------------------------

ALTER TABLE content_ideas
  ADD COLUMN IF NOT EXISTS pack_id         uuid REFERENCES content_packs(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS format_slug     text CHECK (format_slug IN (
    'breaking_alert', 'meme_concept', 'carousel_concept', 'reel_concept',
    'story_poll', 'hot_take', 'controversial_take', 'caption_options',
    'comment_bait_cta', 'visual_direction', 'safer_version', 'sharper_version', 'savage_version'
  )),
  ADD COLUMN IF NOT EXISTS output_style    text CHECK (output_style IN (
    'mainstream', 'savage', 'safer', 'editorial', 'deadpan', 'mock_serious'
  )),
  ADD COLUMN IF NOT EXISTS structured_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS confidence_score int CHECK (confidence_score >= 0 AND confidence_score <= 100),
  ADD COLUMN IF NOT EXISTS estimated_cost_usd numeric(10, 6);

COMMENT ON COLUMN content_ideas.pack_id IS 'FK to content_packs — groups all formats from a single generation run.';
COMMENT ON COLUMN content_ideas.format_slug IS 'One of the 13 content format slugs generated by the OUTRAGE engine.';
COMMENT ON COLUMN content_ideas.output_style IS 'Tone/style used when generating this idea.';
COMMENT ON COLUMN content_ideas.structured_data IS 'Full rich structured output from OpenAI (varies by format_slug).';

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_content_ideas_pack_id     ON content_ideas(pack_id);
CREATE INDEX IF NOT EXISTS idx_content_ideas_format_slug ON content_ideas(format_slug);
CREATE INDEX IF NOT EXISTS idx_content_ideas_output_style ON content_ideas(output_style);

-- ---------------------------------------------------------------------------
-- 3. RLS for content_packs
-- ---------------------------------------------------------------------------

ALTER TABLE content_packs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "org_members_read_content_packs"
  ON content_packs FOR SELECT
  TO authenticated
  USING (org_id = ANY(auth.user_org_ids()));

CREATE POLICY "org_editors_manage_content_packs"
  ON content_packs FOR ALL
  TO authenticated
  USING (
    org_id IN (
      SELECT org_id FROM org_members
      WHERE user_id = auth.uid()
        AND role IN ('owner', 'admin', 'editor')
    )
  )
  WITH CHECK (
    org_id IN (
      SELECT org_id FROM org_members
      WHERE user_id = auth.uid()
        AND role IN ('owner', 'admin', 'editor')
    )
  );

CREATE POLICY "service_role_manage_content_packs"
  ON content_packs FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- ---------------------------------------------------------------------------
-- 4. updated_at trigger for content_packs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER set_content_packs_updated_at
  BEFORE UPDATE ON content_packs
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 5. Useful view — content_ideas with pack context
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW v_content_ideas_with_pack AS
SELECT
  ci.*,
  cp.output_style     AS pack_style,
  cp.model_used       AS pack_model,
  cp.status           AS pack_status,
  cp.tokens_used      AS pack_tokens,
  cp.estimated_cost_usd AS pack_cost,
  cp.created_at       AS pack_created_at,
  tc.title            AS cluster_title,
  tc.category         AS cluster_category,
  tc.overall_score    AS cluster_score
FROM content_ideas ci
LEFT JOIN content_packs cp  ON ci.pack_id     = cp.id
LEFT JOIN trend_clusters tc ON ci.cluster_id  = tc.id;

COMMENT ON VIEW v_content_ideas_with_pack IS 'Content ideas enriched with pack and cluster metadata for UI display.';
