// ─── Command Registry ─────────────────────────────────────────────────────────
// All commands available in the command bar.
// cmdk searches across id + label + description + keywords.

import type { StaticCommand } from './command.types'

export const COMMAND_REGISTRY: StaticCommand[] = [

  // ── Navigate ────────────────────────────────────────────────────────────────

  {
    id: 'nav-dashboard',
    label: 'Go to Dashboard',
    description: 'Main overview and quick stats',
    icon: '🏠',
    category: 'navigate',
    keywords: ['home', 'dashboard', 'overview', 'main'],
    href: '/',
  },
  {
    id: 'nav-radar',
    label: 'Go to Viral Radar',
    description: 'Live trend signal feed',
    icon: '📡',
    category: 'navigate',
    keywords: ['radar', 'viral', 'feed', 'signals', 'live'],
    href: '/radar',
  },
  {
    id: 'nav-trends',
    label: 'Go to Trends',
    description: 'All active trend clusters',
    icon: '📈',
    category: 'navigate',
    keywords: ['trends', 'clusters', 'topics', 'stories'],
    href: '/trends',
  },
  {
    id: 'nav-content',
    label: 'Go to Content Ideas',
    description: 'AI-generated post ideas',
    icon: '💡',
    category: 'navigate',
    keywords: ['content', 'ideas', 'generation', 'ai', 'write'],
    href: '/content',
  },
  {
    id: 'nav-memes',
    label: 'Go to Meme Studio',
    description: 'Create memes from trends',
    icon: '😂',
    category: 'navigate',
    keywords: ['meme', 'studio', 'create', 'format', 'template'],
    href: '/memes',
  },
  {
    id: 'nav-pipeline',
    label: 'Go to Pipeline',
    description: 'Content kanban board',
    icon: '🗂️',
    category: 'navigate',
    keywords: ['pipeline', 'kanban', 'board', 'drafts', 'workflow'],
    href: '/pipeline',
  },
  {
    id: 'nav-calendar',
    label: 'Go to Calendar',
    description: 'Schedule and plan posts',
    icon: '📅',
    category: 'navigate',
    keywords: ['calendar', 'schedule', 'plan', 'posts', 'dates'],
    href: '/calendar',
  },
  {
    id: 'nav-assets',
    label: 'Go to Asset Library',
    description: 'Logos, templates, media files',
    icon: '🖼️',
    category: 'navigate',
    keywords: ['assets', 'library', 'files', 'images', 'logos', 'media'],
    href: '/assets',
  },
  {
    id: 'nav-competitors',
    label: 'Go to Competitor Watchlist',
    description: 'Track competitor accounts and feeds',
    icon: '🔍',
    category: 'navigate',
    keywords: ['competitors', 'watchlist', 'rivals', 'monitor', 'track'],
    href: '/competitors',
  },
  {
    id: 'nav-gaps',
    label: 'Go to Gap Analysis',
    description: 'Stories competitors missed',
    icon: '🎯',
    category: 'navigate',
    keywords: ['gaps', 'missed', 'opportunity', 'whitespace', 'competitor'],
    href: '/competitors?tab=gaps',
  },
  {
    id: 'nav-alerts',
    label: 'Go to Alerts',
    description: 'Notifications and alert rules',
    icon: '🔔',
    category: 'navigate',
    keywords: ['alerts', 'notifications', 'rules', 'inbox', 'digest'],
    href: '/alerts',
  },
  {
    id: 'nav-performance',
    label: 'Go to Performance',
    description: 'Post analytics and learning',
    icon: '📊',
    category: 'navigate',
    keywords: ['performance', 'analytics', 'stats', 'metrics', 'data'],
    href: '/performance',
  },
  {
    id: 'nav-settings',
    label: 'Go to Settings',
    description: 'Account and org preferences',
    icon: '⚙️',
    category: 'navigate',
    keywords: ['settings', 'account', 'preferences', 'config'],
    href: '/settings',
  },

  // ── Smart Queries ───────────────────────────────────────────────────────────

  {
    id: 'q-post-now',
    label: 'What should I post now?',
    description: 'Shows your highest-urgency post-now opportunities',
    icon: '⚡',
    category: 'query',
    keywords: ['post now', 'what post', 'should post', 'urgent post', 'best post', 'post today'],
    queryIntent: 'post_now',
    shortcut: '⌘P',
  },
  {
    id: 'q-hottest',
    label: 'Show hottest trends',
    description: 'Top trends by overall priority score',
    icon: '🔥',
    category: 'query',
    keywords: ['hottest', 'top trends', 'best trends', 'viral', 'trending now', 'priority'],
    queryIntent: 'hottest',
  },
  {
    id: 'q-meme-ready',
    label: 'Show best meme-ready trends',
    description: 'Trends with highest meme potential',
    icon: '😂',
    category: 'query',
    keywords: ['meme ready', 'meme worthy', 'meme potential', 'best meme', 'meme format', 'meme trends'],
    queryIntent: 'meme_ready',
  },
  {
    id: 'q-urgent',
    label: 'Show urgent opportunities',
    description: 'High-urgency trends with closing windows',
    icon: '🚨',
    category: 'query',
    keywords: ['urgent', 'critical', 'time sensitive', 'window closing', 'act now', 'opportunity'],
    queryIntent: 'urgent',
  },
  {
    id: 'q-celebrity',
    label: 'Show celebrity stories',
    description: 'Hottest celebrity-related trend clusters',
    icon: '⭐',
    category: 'query',
    keywords: ['celebrity', 'celeb', 'famous', 'star', 'drama', 'beef'],
    queryIntent: 'search',
    queryKeyword: 'celebrity',
  },
  {
    id: 'q-reality-tv',
    label: 'Show reality TV trends',
    description: 'Reality TV and drama content',
    icon: '📺',
    category: 'query',
    keywords: ['reality tv', 'reality show', 'drama', 'bachelor', 'survivor', 'housewives'],
    queryIntent: 'search',
    queryKeyword: 'reality tv',
  },
  {
    id: 'q-gaps',
    label: 'Show stories competitors missed',
    description: 'Uncovered trends your competitors haven\'t touched',
    icon: '🎯',
    category: 'query',
    keywords: ['missed', 'gaps', 'competitors missed', 'whitespace', 'opportunity', 'uncovered'],
    queryIntent: 'competitor_gaps',
  },
  {
    id: 'q-risky',
    label: 'Show risky trends to avoid',
    description: 'Low brand-safety trends — handle with care',
    icon: '⚠️',
    category: 'query',
    keywords: ['risky', 'dangerous', 'brand safety', 'avoid', 'controversial', 'careful'],
    queryIntent: 'risky',
  },

  // ── Actions ─────────────────────────────────────────────────────────────────

  {
    id: 'action-capture-idea',
    label: 'Capture idea',
    description: 'Quickly save a raw idea to the pipeline idea bank',
    icon: '✍️',
    category: 'action',
    keywords: ['capture', 'idea', 'quick', 'note', 'pipeline', 'save', 'draft', 'jot'],
    actionId: 'capture_idea',
    shortcut: '⌘⇧I',
  },
  {
    id: 'action-fire-alerts',
    label: 'Fire alert rules',
    description: 'Evaluate all alert rules against current trends now',
    icon: '⚡',
    category: 'action',
    keywords: ['fire', 'alerts', 'check now', 'evaluate', 'rules', 'notifications'],
    actionId: 'fire_alerts',
  },
  {
    id: 'action-morning-digest',
    label: 'Generate morning digest',
    description: 'Create and preview today\'s morning briefing',
    icon: '🌅',
    category: 'action',
    keywords: ['morning', 'digest', 'briefing', 'daily', 'summary', 'generate'],
    actionId: 'morning_digest',
  },
  {
    id: 'action-evening-digest',
    label: 'Generate evening digest',
    description: 'Create tonight\'s performance recap',
    icon: '🌆',
    category: 'action',
    keywords: ['evening', 'digest', 'recap', 'daily', 'summary', 'night'],
    actionId: 'evening_digest',
  },
  {
    id: 'action-refresh-competitors',
    label: 'Refresh competitor feeds',
    description: 'Pull latest RSS/Atom posts from all competitors',
    icon: '🔄',
    category: 'action',
    keywords: ['refresh', 'competitors', 'fetch', 'feeds', 'update', 'rss'],
    actionId: 'refresh_competitors',
  },
  {
    id: 'action-log-performance',
    label: 'Log post performance',
    description: 'Record a post\'s metrics and learn from results',
    icon: '📊',
    category: 'action',
    keywords: ['log', 'performance', 'post', 'metrics', 'stats', 'results', 'analytics'],
    href: '/performance',
    actionId: 'log_performance',
  },

  // ── Generate ────────────────────────────────────────────────────────────────

  {
    id: 'gen-headlines',
    label: 'Generate headline options',
    description: 'AI headline variations for the current trend',
    icon: '✍️',
    category: 'generate',
    keywords: ['generate', 'headline', 'title', 'hook', 'options', 'ai', 'write'],
    href: '/content',
    actionId: 'generate_headlines',
  },
  {
    id: 'gen-meme',
    label: 'Create meme from trend',
    description: 'Open Meme Studio with current trend context',
    icon: '🎨',
    category: 'generate',
    keywords: ['create', 'meme', 'generate', 'template', 'format', 'funny'],
    href: '/memes',
    actionId: 'create_meme',
  },
  {
    id: 'gen-canva',
    label: 'Export to Canva',
    description: 'Send current trend data to Canva design flow',
    icon: '🎨',
    category: 'generate',
    keywords: ['export', 'canva', 'design', 'graphic', 'visual', 'template'],
    href: '/content',
    actionId: 'export_canva',
  },
  {
    id: 'gen-savage',
    label: 'Make this more savage',
    description: 'Rewrite current content in aggressive brand voice',
    icon: '🔥',
    category: 'generate',
    keywords: ['savage', 'aggressive', 'spicy', 'edgy', 'rewrite', 'voice', 'brand', 'hot take'],
    href: '/brand',
    actionId: 'rewrite_savage',
  },
]

// Indexed by id for fast lookup
export const COMMAND_MAP = Object.fromEntries(COMMAND_REGISTRY.map((c) => [c.id, c]))
